# Generated by Django 2.2.7 on 2020-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200125_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название услуги'),
        ),
    ]
